### PR TITLE
fix(panos_nat_rule): fix panos_nat_rule helper params

### LINKED ISSUE #380: panos_nat_rule does not work with paloaltonetworks.panos newer than v2.9.0
## Describe the bug

after updating paloaltonetworks.panos collection to v2.13.0, panos_nat_rule fails with the following error message:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'check_mode'
failed: [paloalto.host.name] (item={'name': '***************', 'desc': 'NAT Regel ****** zur ***************', 'source_zone': '******', 'source_ip': '**********', 'destination_ip': '*********************-all', 'destination_zone': '***************', 'to_interface': 'mytunnel', 'service': 'any', 'snat_type': 'static-ip', 'snat_interface_address': '***************', 'snat_bidirectional': 'yes'}) => {"ansible_loop_var": "item", "changed": false, "item": {"desc": "NAT Regel dom01 zur ***************", "destination_ip": "*********************-all", "destination_zone": "***************", "name": "***************", "service": "any", "snat_bidirectional": "yes", "snat_interface_address": "***************", "snat_type": "static-ip", "source_ip": "**********", "source_zone": "******", "to_interface": "mytunnel"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/jzi/.ansible/tmp/ansible-tmp-1674581875.8790898-3613271-56785227633556/AnsiballZ_panos_nat_rule.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/jzi/.ansible/tmp/ansible-tmp-1674581875.8790898-3613271-56785227633556/AnsiballZ_panos_nat_rule.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jzi/.ansible/tmp/ansible-tmp-1674581875.8790898-3613271-56785227633556/AnsiballZ_panos_nat_rule.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_nat_rule', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_nat_rule', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_panos_nat_rule_payload_107771sw/ansible_panos_nat_rule_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_nat_rule.py\", line 542, in <module>\n  File \"/tmp/ansible_panos_nat_rule_payload_107771sw/ansible_panos_nat_rule_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_nat_rule.py\", line 524, in main\n  File \"/tmp/ansible_panos_nat_rule_payload_107771sw/ansible_panos_nat_rule_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py\", line 567, in apply_state\nAttributeError: 'NoneType' object has no attribute 'check_mode'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

This problem was introduced with the collection version v2.10.0

## Expected behavior

The module should add the configured NAT rules as in version v2.9.0
The release notes do not contain notes about breaking changes.
According to the documentation the module will be removed with version 3.x, so I would expect that the modules still works in any v2.x version

## Current behavior

The modules fails with error about accessing check_mode in NoneType object

## Steps to reproduce

run playbook containing panos_nat_rule module with collection v. >2.9.0

## Your Environment

- Collection: paloaltonetworks.panos v2.13.0
- Python: 3.9.14
- Ansible: 2.13.3
- PAN-OS Python Library & version: pan-os-python v1.7.3 , pan-python v0.17.0

### PR DESCRIPTION
**Pull request by jamesholland-uk**
## Description
Fix for params in helper

## Motivation and Context
Fixes #380

## How Has This Been Tested?
Tested locally, patching local collection

## Screenshots (if appropriate)
Testing, before and after
Screenshot 2023-01-25 at 13 01 11

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by shinmog — APPROVED** [review]
lgtm
